### ISSUE TITLE
URLs are wrong if you go to /admin/

### ISSUE THREAD

**Issue by dpash** [stephenjude/filament-debugger#10]
If you go to http://localhost/admin/ the links are http://localhost/admin/telescope and http://localhost/admin/horizon. 

If you go to http://localhost/admin (notice the lack of trailing slash) the links are correctly http://localhost/telescope and http://localhost/horizon.

**Comment by stephenjude** [comment]
@dpash can you submit a quick fix PR for this?

**Comment by dpash** [comment]
Unfortunately I was unable to find what's causing the issue.

**Comment by stephenjude** [comment]
Okay, I will look and see if I can find anything, but I think the issue might result from not using a defined tld. Have tried running your app on Valet or Homestead?

**Comment by richardtoth94** [comment]
I've opened a PR for this 

#12

**Comment by stephenjude** [comment]
Thanks @richardtoth94
