### ISSUE TITLE
Documentation Issue - 

### ISSUE THREAD

**Issue by OccTherapist** [stephenjude/filament-debugger#32]
The documentation page uses this example for authorization

`->authorize(condition: fn() => auth()->user()->can('view.debuggers'))`

But this throws an error, because auth()->user() is not available in a service provider. The auth session is created after the service providers are executed.

**Comment by stephenjude** [comment]
Hi @OccTherapist 

I have tagged a release that fixed this. Let me know if that solves it for you. 

https://github.com/stephenjude/filament-debugger/releases/tag/3.1.1

**Comment by lazar89nis** [comment]
Looks like there is still this problem. I am on 3.1.3 and I get this same rror

**Comment by anhofmann** [comment]
You can't use the code as it is, because you haven't set up a 'view.debuggers' permission in your project. You have to implement your own logic here.
