### ISSUE TITLE
Feature request - support laravel 10

### ISSUE THREAD

**Issue by G3z** [stephenjude/filament-debugger#6]
`illuminate/contracts`should be upgraded to `10.0`
`stephenjude/filament-debugger 1.0.0 requires illuminate/contracts ^8.73|^9.0 -> satisfiable by illuminate/contracts[v8.73.0, ..., v8.83.27, v9.0.0, ..., v9.52.0].`

**Comment by stephenjude** [comment]
@G3z can you make a PR
